exempt=[
    "class{^jghost\\/}",
    "class{Dump}",
    "class{^org\\/jnativehook\\/}",
    "class{^com\\/sun\\/jna\\/}",
    "class{FrameComputer}",
    "class{util}",
    "class{PredicateFactory}"
]
flowCondition {
    enabled=true
}
flowException {
    decoyCalls {
        enabled=false
        includeLibraries=false
        maxArgs=5
        scope=APPLICATION_AND_EXEMPT
    }
    enabled=true
    strength=AGGRESSIVE
}
flowRange {
    enabled=true
}
methodDispatch {
    enabled=false
    scope=APP_ONLY
    maxPerDispatcher=64
    decoyDefaultCalls=false
}
methodMerge {
    enabled=false
    maxPerHost=16
    maxHostInsns=20000
}
signatureObfuscation {
    enabled=false
    arguments=true
    returns=false
    returnThreadKey=false
}
native {
    enabled=false
}
numberEncryption {
    enabled=true
}
stringEncryption {
    enabled=true
    type=STANDARD
}
