exempt=[
    "class{^jghost\\/}",
    "class{Dump}",
    "class{^org\\/jnativehook\\/}",
    "class{^com\\/sun\\/jna\\/}",
    "class{FrameComputer}",
    "class{util}",
    "class{PredicateFactory}"
]
flowCondition {
    enabled=true
}
flowException {
    enabled=false
}
flowRange {
    enabled=false
}
flowSwitch {
    enabled=false
}
interprocedural {
    enabled=true
    threadStaticMethods=true
}
methodCallObfuscation {
    enabled=true
}
methodDispatch {
    enabled=false
}
methodMerge {
    enabled=false
}
signatureObfuscation {
    enabled=false
}
native {
    enabled=false
}
numberEncryption {
    enabled=true
}
stringEncryption {
    enabled=false
}
sdk {
    enabled=false
}
ahegao {
    enabled=false
}
pureEncryption {
    enabled=false
}
stringEqualsHash {
    enabled=false
}
stringEqIgCaseHash {
    enabled=false
}
typeCheck {
    enabled=false
}
