exempt=[
    "class{^jghost\\/}",
    "class{Dump}",
    "class{^org\\/jnativehook\\/}",
    "class{^com\\/sun\\/jna\\/}"
]
fileCrasher {
    enabled=true
}
flowCondition {
    enabled=true
}
flowException {
    enabled=true
    strength=AGGRESSIVE
}
flowRange {
    enabled=true
}
flowSwitch {
    enabled=true
}
interprocedural {
    enabled=true
    threadStaticMethods=true
}
methodCallObfuscation {
    enabled=true
}
methodDispatch {
    enabled=true
    maxPerDispatcher=64
    scope="INCLUDE_LIBRARY"
}
methodMerge {
    enabled=false
    maxHostInsns=20000
    maxPerHost=16
}
native {
    enabled=false
}
numberEncryption {
    enabled=true
}
sdk {
    enabled=true
}
signatureObfuscation {
    enabled=true
}
stringEncryption {
    enabled=true
    type=STANDARD
}
ahegao {
    enabled=true
}
